export default {
  blue: "#007AFF",
  lightGrey: "#F0F0F0",
  nearlyWhite: "#F8F8F8",
  grey: "#D8D8D8",
  defaultTextColor: "#333333",
  primary: "#007AFF",
  white: "white",
  black: "black",
  red: "red",
  beige: "#F5F5DC",
  orange: "#ffA100",
  lightGreyBubble: "#f1f1f1",
  translationBubble: "#7c5e4b",
  translationBubbleColor: "#72513c",
  flashCard: "#ffefe2",
  flashCardAnswer: "#FFEEDE",
  darkModeBubble: "#1c1c1c",
  darkmodeChatBackground: "#1c1c1c",
  darkModePageBackground: "#1c1c1c",
};
