const i18n = new I18n({
  enableFallback: true,
  "en-US": {
    appName: "Langiddy",
    welcome: "Welcome to Langiddy",
    "Select languages below, then tap save":
      "Select languages below, then tap save",

    Giddy: "Giddy!",
    Hidden: "Hidden",
    "Info saved, Happy chatting!": "Info saved. Happy chatting!",
    Tutorials: "Tutorials",
    Home: "Home",
    "Invite friends": "Invite friends",
    "I'm fluent in": "I'm fluent in",
    "I'm learning": "I'm learning",
    "I'm interested in": "I'm interested in",
    "Update Langs status": "Update Langs status",
    "About me": "About me",
    "Restore purchases": "Restore purchases",
    "Next trip (optional)": "Next trip (optional)",
    "Restore purchases": "Restore purchases",
    "Account settings": "Account settings",
    "Hide profile or make it visible to other users":
      "Hide profile or make it visible to other users",
    "Tap to edit your name": "Tap to edit your name",
    "Edit first name": "Edit first name",
    "Edit last name": "Edit last name",
    "Fluent language is the language you are most comfortable speaking or born speaking":
      "Fluent language is the language you are most comfortable speaking or born speaking",
    Save: "Save",
    "Select the language you are fluent in (required)":
      "Select the language you are fluent in (required)",
    "Select the language you want to learn (required)":
      "Select the language you want to learn (required)",
    "Select an additional language you want to learn (optional)":
      "Select an additional language you want to learn (optional)",
    Africkaans: "Africkaans",
    Albanian: "Albanian",
    Amharic: "Amharic",
    Arabic: "Arabic",
    Armenian: "Armenian",
    Azerbaijani: "Azerbaijani",
    Bashkir: "Bashkir",
    Basque: "Basque",
    Belarusian: "Belarusian",
    Bengali: "Bengali",
    Bosnian: "Bosnian",
    Bulgarian: "Bulgarian",
    Catalan: "Catalan",
    Cebuano: "Cebuano",
    Chichewa: "Chichewa",
    "Chinese Simplified": "Chinese Simplified",
    "Chinese Traditional": "Chinese Traditional",
    Corsican: "Corsican",
    Croatian: "Croatian",
    Czech: "Czech",
    Danish: "Danish",
    Dutch: "Dutch",
    English: "English",
    Esperanto: "Esperanto",
    Estonian: "Estonian",
    Finnish: "Finnish",
    French: "French",
    Frisian: "Frisian",
    Galician: "Galician",
    Georgian: "Georgian",
    German: "German",
    Greek: "Greek",
    Gujarati: "Gujarati",
    "Haitian Creole": "Haitian Creole",
    Haitian: "Haitian",
    Hausa: "Hausa",
    Hawaiian: "Hawaiian",
    Hebrew: "Hebrew",
    Hindi: "Hindi",
    Hmong: "Hmong",
    Hungarian: "Hungarian",
    Icelandic: "Icelandic",
    Igbo: "Igbo",
    Indonesian: "Indonesian",
    Irish: "Irish",
    Italian: "Italian",
    Japanese: "Japanese",
    Javanese: "Javanese",
    Kannada: "Kannada",
    Kazakh: "Kazakh",
    Khmer: "Khmer",
    Kinyarwanda: "Kinyarwanda",
    Korean: "Korean",
    Kurdish: "Kurdish",
    Kyrgyz: "Kyrgyz",
    Lao: "Lao",
    Latin: "Latin",
    Latvian: "Latvian",
    Lithuanian: "Lithuanian",
    Luxembourgish: "Luxembourgish",
    Macedonian: "Macedonian",
    Malagasy: "Malagasy",
    Malay: "Malay",
    Malayalam: "Malayalam",
    Maltese: "Maltese",
    Maori: "Maori",
    Marathi: "Marathi",
    Mongolian: "Mongolian",
    Myanmar: "Myanmar",
    Nepali: "Nepali",
    Norwegian: "Norwegian",
    Nyanja: "Nyanja",
    Pashto: "Pashto",
    Persian: "Persian",
    Polish: "Polish",
    Portuguese: "Portuguese",
    Punjabi: "Punjabi",
    Romanian: "Romanian",
    Russian: "Russian",
    Samoan: "Samoan",
    "Scots Gaelic": "Scots Gaelic",
    Serbian: "Serbian",
    Sesotho: "Sesotho",
    Shona: "Shona",
    Sindhi: "Sindhi",
    Sinhala: "Sinhala",
    Slovak: "Slovak",
    Slovenian: "Slovenian",
    Somali: "Somali",
    Spanish: "Spanish",
    Sundanese: "Sundanese",
    Swahili: "Swahili",
    Swedish: "Swedish",
    Tagalog: "Tagalog",
    Tajik: "Tajik",
    Tamil: "Tamil",
    Telugu: "Telugu",
    Thai: "Thai",
    Turkish: "Turkish",
    Ukrainian: "Ukrainian",
    Urdu: "Urdu",
    Uzbek: "Uzbek",
    Vietnamese: "Vietnamese",
    Welsh: "Welsh",
    Xhosa: "Xhosa",
    Yiddish: "Yiddish",
    Yoruba: "Yoruba",
    Zulu: "Zulu",
    "Update status for Langs": "Update status for Langs",
    "Let people know what you want to talk about today":
      "Let people know what you want to talk about today",
    "Occupation (optional)": "Occupation (optional)",
    "What do you do for a living?": "What do you do for a living?",
    "Account settings": "Account settings",
  },
  "en-MX": {
    appName: "Langiddy",
    welcome: "Bienvenido a Langiddy",
    "Select languages below, then tap save":
      "Seleccione los idiomas a continuación, luego toque guardar",
    Giddy: "Emocionado!",
    Hidden: "Oculto",
    "Info saved, Happy chatting!": "Información guardada. ¡Feliz charla!",
    Tutorials: "Tutoriales",
    Home: "Casa",
    "Invite friends": "Invitar amigos",
    "I'm fluent in": "Hablo con fluidez",
    "I'm learning": "Estoy aprendiendo",
    "I'm interested in": "Estoy interesado en",
    "Update Langs status": "Actualizar estado de Langs",
    "Restore purchases": "Restaurar compras",
    "Account settings": "Configuraciones de la cuenta",
    "Hide profile or make it visible to other users":
      "Ocultar perfil o hacerlo visible para otros usuarios",
    "Tap to edit your name": "Toque para editar su nombre",
    "Edit first name": "Editar primer nombre",
    "Edit last name": "Editar apellido",
    "Fluent language is the language you are most comfortable speaking or born speaking":
      "El idioma fluido es el idioma que más cómodo habla o nace hablando",
    Save: "Salvar",
    "Select the language you are fluent in (required)":
      "Seleccione el idioma en el que es fluido (requerido)",
    "Select the language you want to learn (required)":
      "Seleccione el idioma que desea aprender (requerido)",
    "Select an additional language you want to learn (optional)":
      "Seleccione un idioma adicional que desee aprender (opcional)",
    Africkaans: "Africkaans",
    Albanian: "Albanés",
    Amharic: "Amárico",
    Arabic: "Arábica",
    Armenian: "Armenio",
    Azerbaijani: "Azerbaiyano",
    Bashkir: "Bashkir",
    Basque: "Vasco",
    Belarusian: "Bielorruso",
    Bengali: "Bengalí",
    Bosnian: "Bosnio",
    Bulgarian: "Búlgaro",
    Burmese: "Birmano",
    Catalan: "Catalán",
    Cebuano: "Cebuano",
    Chichewa: "Chichewa",
    "Chinese Simplified": "Chino simplificado",
    "Chinese Traditional": "Chino tradicional",
    Corsican: "Corso",
    Croatian: "Croata",
    Czech: "Checo",
    Danish: "Danés",
    Dutch: "Holandés",
    English: "Inglés",
    Esperanto: "Esperanto",
    Estonian: "Estonio",
    Finnish: "Finlandés",
    French: "Francés",
    Frisian: "Frisón",
    Galician: "Gallego",
    Georgian: "Georgiano",
    German: "Alemán",
    Greek: "Griego",
    Gujarati: "Guyaratí",
    "Haitian Creole": "Criollo haitiano",
    Hausa: "Hausa",
    Hawaiian: "Hawaiano",
    Hebrew: "Hebreo",
    Hindi: "Hindi",
    Hmong: "Hmong",
    Hungarian: "Húngaro",
    Icelandic: "Islandés",
    Igbo: "Igbo",
    Indonesian: "Indonesio",
    Irish: "Irlandés",
    Italian: "Italiano",
    Japanese: "Japonés",
    Javanese: "Javanés",
    Kannada: "Canarés",
    Kazakh: "Kazajo",
    Khmer: "Jemer",
    Korean: "Coreano",
    Kurdish: "Kurdo",
    Kyrgyz: "Kirguís",
    Lao: "Lao",
    Latin: "Latín",
    Latvian: "Letón",
    Lithuanian: "Lituano",
    Luxembourgish: "Luxemburgués",
    Macedonian: "Macedonio",
    Malagasy: "Malgache",
    Malay: "Malayo",
    Malayalam: "Malayalam",
    Maltese: "Maltés",
    Maori: "Maorí",
    Marathi: "Marathi",
    Mongolian: "Mongol",
    Myanmar: "Myanmar",
    Nepali: "Nepalí",
    Norwegian: "Noruego",
    Pashto: "Pastún",
    Persian: "Persa",
    Polish: "Polaco",
    Portuguese: "Portugués",
    Punjabi: "Panyabí",
    Romanian: "Rumano",
    Russian: "Ruso",
    Samoan: "Samoano",
    "Scots Gaelic": "Gaélico escocés",
    Serbian: "Serbio",
    Sesotho: "Sesotho",
    Shona: "Shona",
    Sindhi: "Sindhi",
    Sinhala: "Cingalés",
    Slovak: "Eslovaco",
    Slovenian: "Esloveno",
    Somali: "Somalí",
    Spanish: "Español",
    Sundanese: "Sundanés",
    Swahili: "Swahili",
    Swedish: "Sueco",
    Tagalog: "Tagalo",
    Tajik: "Tayiko",
    Tamil: "Tamil",
    Tatar: "Tártaro",
    Telugu: "Telugu",
    Thai: "Tailandés",
    Turkish: "Turco",
    Turkmen: "Turcomano",
    Ukrainian: "Ucranio",
    Urdu: "Urdu",
    Uyghur: "Uigur",
    Uzbek: "Uzbeko",
    Vietnamese: "Vietnamita",
    Welsh: "Galés",
    Xhosa: "Xhosa",
    Yiddish: "Yiddish",
    Yoruba: "Yoruba",
    Zulu: "Zulú",
    "Update status for Langs": "Actualizar estado para Langs",
    "Let people know what you want to talk about today":
      "Deje que la gente sepa de qué quiere hablar hoy",
    "About me": "Sobre mí",
    "Account settings": "Configuración de la cuenta",
    "Tell us about yourself": "Cuéntanos sobre ti",
    "Occupation (optional)": "Ocupación (opcional)",
    "What do you do for a living?": "¿A qué te dedicas?",
  },
  "en-JP": {
    appName: "Langiddy",
    welcome: "Langiddyへようこそ",
    "Select languages below, then tap save":
      "以下の言語を選択してから、保存をタップします",
    Giddy: "ワクワク！",
    Hidden: "隠し",
    "Info saved, Happy chatting!":
      "情報が保存されました。 チャットを楽しんで！",
    Tutorials: "チュートリアル",
    Home: "ホーム",
    "Invite friends": "友達を招待する",
    "I'm fluent in": "私は流暢です",
    "I'm learning": "私は学んでいます",
    "I'm interested in": "私は興味があります",
    "Update Langs status": "Langsのステータスを更新する",
    "Account settings": "アカウント設定",
    "Restore purchases": "購入を復元する",
    "Account settings": "アカウント設定",
    "Hide profile or make it visible to other users":
      "プロフィールを非表示にするか、他のユーザーに表示する",
    "Tap to edit your name": "名前を編集するにはタップしてください",
    "Edit first name": "名を編集する",
    "Edit last name": "姓を編集する",
    "Fluent language is the language you are most comfortable speaking or born speaking":
      "流暢な言語は、最も快適に話すか、生まれながらにして話す言語です",
    Save: "セーブ",
    "Select the language you are fluent in (required)":
      "流暢な言語を選択してください。 （必須）",
    "Select the language you want to learn (required)":
      "学びたい言語を選択してください。 （必須）",
    "Select an additional language you want to learn (optional)":
      "学びたい追加の言語を選択してください。 （任意）",
    Africkaans: "アフリカーンス語",
    Albanian: "アルバニア語",
    Amharic: "アムハラ語",
    Arabic: "アラビア語",
    Armenian: "アルメニア語",
    Azerbaijani: "アゼルバイジャン語",
    Bashkir: "バシキール語",
    Basque: "バスク語",
    Belarusian: "ベラルーシ語",
    Bengali: "ベンガル語",
    Bosnian: "ボスニア語",
    Bulgarian: "ブルガリア語",
    Burmese: "ビルマ語",
    Catalan: "カタルーニャ語",
    Cebuano: "セブアノ語",
    Chichewa: "チェワ語",
    "Chinese Simplified": "中国語簡体字",
    "Chinese Traditional": "中国語繁体字",
    Corsican: "コルシカ語",
    Croatian: "クロアチア語",
    Czech: "チェコ語",
    Danish: "デンマーク語",
    Dutch: "オランダ語",
    English: "英語",
    Esperanto: "エスペラント語",
    Estonian: "エストニア語",
    Finnish: "フィンランド語",
    French: "フランス語",
    Frisian: "フリジア語",
    Galician: "ガリシア語",
    Georgian: "ジョージア語",
    German: "ドイツ語",
    Greek: "ギリシャ語",
    Gujarati: "グジャラート語",
    "Haitian Creole": "ハイチ語",
    Hausa: "ハウサ語",
    Hawaiian: "ハワイ語",
    Hebrew: "ヘブライ語",
    Hindi: "ヒンディー語",
    Hmong: "モン族",
    Hungarian: "ハンガリー語",
    Icelandic: "アイスランド語",
    Igbo: "イボ語",
    Indonesian: "インドネシア語",
    Irish: "アイルランド語",
    Italian: "イタリア語",
    Japanese: "日本語",
    Javanese: "ジャワ語",
    Kannada: "カンナダ語",
    Kazakh: "カザフ語",
    Khmer: "クメール語",
    Kinyarwanda: "ルワンダ語",
    Korean: "韓国語",
    Kurdish: "クルド語",
    Kyrgyz: "キルギス語",
    Lao: "ラオス語",
    Latin: "ラテン語",
    Latvian: "ラトビア語",
    Lithuanian: "リトアニア語",
    Luxembourgish: "ルクセンブルク語",
    Macedonian: "マケドニア語",
    Malagasy: "マダガスカル語",
    Malay: "マレー語",
    Malayalam: "マラヤーラム語",
    Maltese: "マルタ語",
    Maori: "マオリ語",
    Marathi: "マラーティー語",
    Mongolian: "モンゴル語",
    Myanmar: "ミャンマー",
    Nepali: "ネパール語",
    Norwegian: "ノルウェー語",
    Pashto: "パシュトゥー語",
    Persian: "ペルシャ語",
    Polish: "ポーランド語",
    Portuguese: "ポルトガル語",
    Punjabi: "パンジャブ語",
    Romanian: "ルーマニア語",
    Russian: "ロシア語",
    Samoan: "サモア語",
    "Scots Gaelic": "スコットランドゲール語",
    Serbian: "セルビア語",
    Sesotho: "セソト語",
    Shona: "ショナ語",
    Sindhi: "シンド語",
    Sinhala: "シンハラ語",
    Slovak: "スロバキア語",
    Slovenian: "スロベニア語",
    Somali: "ソマリ語",
    Spanish: "スペイン語",
    Sundanese: "スンダ語",
    Swahili: "スワヒリ語",
    Swedish: "スウェーデン語",
    Tagalog: "タガログ語",
    Tajik: "タジク語",
    Tamil: "タミル語",
    Telugu: "テルグ語",
    Thai: "タイ語",
    Turkish: "トルコ語",
    Ukrainian: "ウクライナ語",
    Urdu: "ウルドゥー語",
    Uzbek: "ウズベク語",
    Vietnamese: "ベトナム語",
    Welsh: "ウェールズ語",
    Xhosa: "コサ語",
    Yiddish: "イディッシュ語",
    Yoruba: "ヨルバ語",
    Zulu: "ズールー語",
    "Update status for Langs": "Langsのステータスを更新する",
    "Let people know what you want to talk about today":
      "今日話したいことを人々に知らせてください。",
    "About me": "私について",
    "Tell us about yourself": "あなた自身について教えてください",
    "Occupation (optional)": "職業（任意）",
    "What do you do for a living?": "あなたはどんな仕事をしていますか？",
  },
  "en-CN": {
    "Update status for Langs": "更新Langs的状态",
    "Let people know what you want to talk about today":
      "让人们知道你今天想谈什么",
    "About me": "关于我",
    "Tell us about yourself": "告诉我们关于你自己",
    "Occupation (optional)": "职业（可选）",
    "What do you do for a living?": "你是做什么的？",
    appName: "Langiddy",
    Giddy: "Giddy",
    Hidden: "隐藏",
    Home: "首页",
    Tutorials: "教程",
    "I'm fluent in": "我精通",
    "I'm learning": "我在学习",
    "I'm interested in": "我对...感兴趣",
    "Update Langs status": "更新语言状态",
    "Restore purchases": "恢复购买",
    "Account settings": "账户设置",
    "Hide profile or make it visible to other users":
      "隐藏个人资料或使其对其他用户可见",
    "Tap to edit your name": "点击编辑你的名字",
    "Edit first name": "编辑名字",
    "Edit last name": "编辑姓氏",
    Save: "保存",
    "Select languages below, then tap save": "在下面选择语言，然后点击保存",
    Africkaans: "南非荷兰语",
    Albanian: "阿尔巴尼亚语",
    Amharic: "阿姆哈拉语",
    Arabic: "阿拉伯语",
    Armenian: "亚美尼亚语",
    Azerbaijani: "阿塞拜疆语",
    Bashkir: "巴什基尔语",
    Basque: "巴斯克语",
    Belarusian: "白俄罗斯语",
    Bengali: "孟加拉语",
    Bosnian: "波斯尼亚语",
    Bulgarian: "保加利亚语",
    Burmese: "缅甸语",
    Catalan: "加泰罗尼亚语",
    Cebuano: "宿雾语",
    Chichewa: "奇切瓦语",
    "Chinese Simplified": "简体中文",
    "Chinese Traditional": "繁体中文",
    Corsican: "科西嘉语",
    Croatian: "克罗地亚语",
    Czech: "捷克语",
    Danish: "丹麦语",
    Dutch: "荷兰语",
    English: "英语",
    Esperanto: "世界语",
    Estonian: "爱沙尼亚语",
    Finnish: "芬兰语",
    French: "法语",
    Frisian: "弗里斯兰语",
    Galician: "加利西亚语",
    Georgian: "格鲁吉亚语",
    German: "德语",
    Greek: "希腊语",
    Gujarati: "古吉拉特语",
    "Haitian Creole": "海地语",
    Hausa: "豪萨语",
    Hawaiian: "夏威夷语",
    Hebrew: "希伯来语",
    Hindi: "印地语",
    Hmong: "苗语",
    Hungarian: "匈牙利语",
    Icelandic: "冰岛语",
    Igbo: "伊博语",
    Indonesian: "印度尼西亚语",
    Irish: "爱尔兰语",
    Italian: "意大利语",
    Japanese: "日语",
    Javanese: "爪哇语",
    Kannada: "卡纳达语",
    Kazakh: "哈萨克语",
    Khmer: "高棉语",
    Kinyarwanda: "基尼亚卢旺达语",
    Korean: "韩语",
    Kurdish: "库尔德语",
    Kyrgyz: "吉尔吉斯语",
    Lao: "老挝语",
    Latin: "拉丁语",
    Latvian: "拉脱维亚语",
    Lithuanian: "立陶宛语",
    Luxembourgish: "卢森堡语",
    Macedonian: "马其顿语",
    Malagasy: "马达加斯加语",
    Malay: "马来语",
    Malayalam: "马拉雅拉姆语",
    Maltese: "马耳他语",
    Maori: "毛利语",
    Marathi: "马拉地语",
    Mongolian: "蒙古语",
    Myanmar: "缅甸语",
    Nepali: "尼泊尔语",
    Norwegian: "挪威语",
    Pashto: "普什图语",
    Persian: "波斯语",
    Polish: "波兰语",
    Portuguese: "葡萄牙语",
    Punjabi: "旁遮普语",
    Romanian: "罗马尼亚语",
    Russian: "俄语",
    Samoan: "萨摩亚语",
    "Scots Gaelic": "苏格兰盖尔语",
    Serbian: "塞尔维亚语",
    Sesotho: "塞索托语",
    Shona: "绍纳语",
    Sindhi: "信德语",
    Sinhala: "僧伽罗语",
    Slovak: "斯洛伐克语",
    Slovenian: "斯洛文尼亚语",
    Somali: "索马里语",
    Spanish: "西班牙语",
    Sundanese: "巽他语",
    Swahili: "斯瓦希里语",
    Swedish: "瑞典语",
    Tagalog: "他加禄语",
    Tajik: "塔吉克语",
    Tamil: "泰米尔语",
    Tatar: "鞑靼语",
    Telugu: "泰卢固语",
    Thai: "泰语",
    Turkish: "土耳其语",
    Turkmen: "土库曼语",
    Ukrainian: "乌克兰语",
    Urdu: "乌尔都语",
    Uyghur: "维吾尔语",
    Uzbek: "乌兹别克语",
    Vietnamese: "越南语",
    Welsh: "威尔士语",
    Xhosa: "科萨语",
    Yiddish: "意第绪语",
    Yoruba: "约鲁巴语",
    Zulu: "祖鲁语",
    "Select the language you are fluent in (required)":
      "选择您精通的语言。（必填）",
    "Select the language you want to learn (required)":
      "选择您想学习的语言。（必填）",
    "Select an additional language you want to learn (optional)":
      "选择您想学习的其他语言。（可选）",
    "Info saved, Happy chatting!": "信息已保存，祝您聊天愉快！",
    "Fluent language is the language you are most comfortable speaking or born speaking":
      "精通语言是您最擅长说或出生说的语言",
  },
});

export default i18n;
